### ISSUE TITLE
ctcdecode install error

### ISSUE THREAD

**Issue by thunder123321** [chenyangh/DSLP#8]
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/home/nihao/anaconda3/envs/DSLP/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1673, in _run_ninja_build
    env=env)
  File "/home/nihao/anaconda3/envs/DSLP/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    cmdclass={'build_ext': BuildExtension}
  File "/home/nihao/anaconda3/envs/DSLP/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/nihao/anaconda3/envs/DSLP/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/nihao/anaconda3/envs/DSLP/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/nihao/anaconda3/envs/DSLP/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/nihao/anaconda3/envs/DSLP/lib/python3.7/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/nihao/anaconda3/envs/DSLP/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/nihao/anaconda3/envs/DSLP/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/nihao/anaconda3/envs/DSLP/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/nihao/anaconda3/envs/DSLP/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/home/nihao/anaconda3/envs/DSLP/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/nihao/anaconda3/envs/DSLP/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 708, in build_extensions
    build_ext.build_extensions(self)
  File "/home/nihao/anaconda3/envs/DSLP/lib/python3.7/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/home/nihao/anaconda3/envs/DSLP/lib/python3.7/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/home/nihao/anaconda3/envs/DSLP/lib/python3.7/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/nihao/anaconda3/envs/DSLP/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/home/nihao/anaconda3/envs/DSLP/lib/python3.7/distutils/command/build_ext.py", line 534, in build_extension
    depends=ext.depends)
  File "/home/nihao/anaconda3/envs/DSLP/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 538, in unix_wrap_ninja_compile
    with_cuda=with_cuda)
  File "/home/nihao/anaconda3/envs/DSLP/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1359, in _write_ninja_file_and_compile_objects
    error_prefix='Error compiling objects for extension')
  File "/home/nihao/anaconda3/envs/DSLP/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1683, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension

env list:
torch 1.8 cuda 11.1
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Is my torch version too high?

**Comment by chenyangh** [comment]
Here is my pip list:
```absl-py                 0.15.0
antlr4-python3-runtime  4.8
arrow                   1.2.2
astroid                 2.9.3
astunparse              1.6.3
byted-torch             1.10.0.post1
cached-property         1.5.2
cachetools              4.2.4
certifi                 2021.10.8
cffi                    1.15.0
charset-normalizer      2.0.10
click                   8.0.3
cloudpickle             2.0.0
colorama                0.4.4
ctcdecode               1.0.3
Cython                  0.29.27
debugpy                 1.5.1
distro-info             0.21
fairseq                 1.0.0a0+a9d3ee1
flatbuffers             1.12
fuzzywuzzy              0.18.0
gast                    0.4.0
google-auth             1.35.0
google-auth-oauthlib    0.4.6
google-pasta            0.2.0
grpcio                  1.34.1
h5py                    3.1.0
hydra-core              1.0.6
idna                    3.3
importlib-metadata      4.10.0
importlib-resources     5.4.0
iotop                   0.6
ipadic                  1.0.0
isort                   5.10.1
joblib                  1.1.0
keras-nightly           2.5.0.dev2021032900
Keras-Preprocessing     1.1.2
lazy-object-proxy       1.7.1
lunanlp                 1.0
Markdown                3.3.6
mccabe                  0.6.1
mecab-python3           1.0.3
ninja                   1.10.2.3
nltk                    3.7
numpy                   1.19.5
oauthlib                3.1.1
omegaconf               2.0.6
opt-einsum              3.3.0
Pillow                  9.0.0
pip                     21.3.1
platformdirs            2.4.1
portalocker             2.0.0
protobuf                3.19.3
psutil                  5.9.0
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pycparser               2.21
pycurl                  7.43.0.2
PyGObject               3.30.4
pylint                  2.12.2
python-apt              1.8.4.3
python-dateutil         2.8.2
python-Levenshtein      0.12.2
PyYAML                  6.0
regex                   2021.11.10
requests                2.27.1
requests-oauthlib       1.3.0
rsa                     4.8
sacrebleu               1.5.1
sacremoses              0.0.47
scikit-learn            1.0.2
scipy                   1.7.3
setuptools              42.0.2
six                     1.15.0
tabulate                0.8.9
tensorboard             2.5.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.1
tensorflow              2.5.0
tensorflow-estimator    2.5.0
tensorrt                8.0.3.4
termcolor               1.1.0
threadpoolctl           3.1.0
toml                    0.10.2
torch                   1.10.1+cu113
torchaudio              0.10.1+cu113
torchvision             0.11.2+cu113
tqdm                    4.62.3
typed-ast               1.5.1
typing-extensions       3.7.4.3
unattended-upgrades     0.1
urllib3                 1.26.7
Werkzeug                2.0.2
wheel                   0.37.1
wrapt                   1.12.1
zipp                    3.7.0
```

**Comment by Vincent131499** [comment]
上面的安装问题解决了吗，我也遇到了同样的问题

**Comment by chenyangh** [comment]
@Vincent131499 You may refer to https://github.com/parlance/ctcdecode and their issues to install the CTC beam search decoder. The installation is usually simple on most platforms.

**Comment by chenyangh** [comment]
@Vincent131499  https://github.com/parlance/ctcdecode/issues
